context:
  version: "4.27"

package:
  name: simpleini
  version: ${{ version }}

source:
  url: https://github.com/brofield/simpleini/archive/refs/tags/v${{ version }}.tar.gz
  sha256: bcf27c6ccab787cb41ee2af430d271b4b483319529978e4e2b1770f14db5627b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - SimpleIni.h
  - script:
      - cmake-package-check SimpleIni
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
about:
  homepage: https://github.com/brofield/simpleini
  summary: Cross-platform C++ library providing a simple API to read and write INI-style configuration files.
  license: MIT
  license_file: LICENCE.txt
  repository: https://github.com/brofield/simpleini

extra:
  recipe-maintainers:
    - olivier-roussel
