context:
  version: "4.26"

package:
  name: simpleini
  version: ${{ version }}

source:
  url: https://github.com/brofield/simpleini/archive/refs/tags/v${{ version }}.tar.gz
  sha256: cfb27ba82570d73ce89d956f15c558d4a79c7ce2ad667a104be2d2f0f12be0cb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja

tests:
  - package_contents:
      include:
        - SimpleIni.h
  - script:
      - cmake-package-check SimpleIni
    requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
about:
  homepage: https://github.com/brofield/simpleini
  summary: Cross-platform C++ library providing a simple API to read and write INI-style configuration files.
  license: MIT
  license_file: LICENCE.txt
  repository: https://github.com/brofield/simpleini

extra:
  recipe-maintainers:
    - olivier-roussel
